language: python
sudo: required
dist: trusty
branches:
  only:
  - travis

python:
  - 2.7
virtualenv:
    system_site_package: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-matplotlib python-numpy python-pandas python-pytest python-scipy python-sklearn python-statsmodels
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
script: ./check.sh
