package:
  name: crosscat
  version: "0.1"

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python 2.7.*
    - cython >=0.20.1
  run:
    - numpy >=1.7.0
    - six

test:
  requires:
    - python 2.7.*
    - pytest 2.5.1.*
  imports:
    - cgpm
  commands:
    - python -m pytest --pyargs cgpm -k "not __ci_"

about:
  home: https://github.com/probcomp/crosscat
  license: Apache
  license_file: LICENSE
